# GitHub Sponsors funding options
github: pedrohmarconato

# Other funding options
# patreon: your-patreon-username
# open_collective: your-open-collective-username
# ko_fi: your-ko-fi-username
# tidelift: npm/your-package-name
# community_bridge: your-project-name
# liberapay: your-liberapay-username
# issuehunt: your-issuehunt-username
# otechie: your-otechie-username
# lfx_crowdfunding: your-lfx-crowdfunding-project-name
# custom: ['https://paypal.me/yourpaypalname', 'https://buy-me-a-coffee.com/yourusername']